name: Create Release on Github Repository
description: 'Create Release on Github Repository'

inputs:
  github_token:
    description: 'Github token'
    required: true
  release_version:
    description: 'Version to release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v0.4.4
      with:
        myToken: ${{ inputs.github_token }}

    - name: Create Release on Github Repository
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ inputs.release_version }}
        release_name: Release v${{ inputs.release_version }}
        body: |
          Grab the new version from Maven central https://repo1.maven.org/maven2/ai/stapi/graph-system/${{ github.event.inputs.releaseversion }}/ by using it in your deps:

          ```
          <dependencies>
              <dependency>
                  <groupId>ai.stapi</groupId>
                  <artifactId>graph-system</artifactId>
                  <version>${{ github.event.inputs.releaseversion }}</version>
              </dependency>
          </dependencies>
          ```

          ### Things that changed in this release
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
