name: Create Release on Github Repository
description: 'Create Release on Github Repository'
runs:
  using: "composite"
  steps:
    - name: Create Release on Github Repository
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.semver.outputs.version }}
        release_name: Release ${{ steps.semver.outputs.version }}
        draft: false
        prerelease: false
