name: Create Release on Github Repository
description: 'Create Release on Github Repository'

inputs:
  github_token:
    description: 'Github token'
    required: true
  release_version:
    description: 'Version to release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Release on Github Repository
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ inputs.release_version }}
        release_name: Release v${{ inputs.release_version }}
        draft: false
        prerelease: false
