name: Publish release to Sonatype
description: 'Publish release to Sonatype'

runs:
  using: "composite"
  steps:
    - name: Echo
      run: mvn -B -U -Possrh,release clean deploy -Dstyle.color=always -e -s $GITHUB_WORKSPACE/settings.xml
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} 
      