name: Commit updated POMs
description: 'Commit updated POMs'

inputs:
  github_token:
    description: 'Github token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Commit updated POMs
      shell: bash
      run: |
        git checkout -b new_branch
        echo ${{ inputs.github_token }}
        git add **/pom.xml
        git commit -m "Update versions to ${{ steps.semver.outputs.version }}"
        git push https://${{ inputs.github_token }}@github.com/standard-api/core.git HEAD:new_branch
