name: Commit updated POMs
description: 'Commit updated POMs'

inputs:
  github_token:
    description: 'Github token'
    required: true
  message:
    description: 'Message to commit'
    required: true

runs:
  using: "composite"
  steps:
    - name: Commit updated POMs
      shell: bash
      run: |
        git add **/pom.xml
        git add pom.xml
        git commit -m "${{ inputs.message }}"
        git push https://${{ inputs.github_token }}@github.com/standard-api/core.git HEAD:master