name: Build and check
description: 'Build with Maven and check with checkstyle and sonar'

runs:
  using: "composite"
  steps:
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Analyze with checkstyle
      run: mvn checkstyle:check -Dcheckstyle.failOnError=true --file pom.xml

    - name: Analyze with sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.branch.name=${GITHUB_REF_NAME} -Dsonar.qualitygate.wait=true --file pom.xml