name: Publish SNAPSHOT to Sonatype
description: 'Publish SNAPSHOT to Sonatype'

inputs:
  ossrh_username:
    description: 'OSSRH usernmae'
    required: true
  ossrh_token:
    description: 'OSSRH token'
    required: true
  ossrh_gpg_secret_key_password:
    description: 'OSSRH GPG secret key password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish SNAPSHOT to Sonatype
      shell: bash
      run: mvn -X -B -U -Possrh,release deploy -Dmaven.security.interactive=false -Dstyle.color=always -DskipTests=true -s ${{ github.workspace }}/settings.xml
      env:
        MAVEN_USERNAME: ${{ inputs.ossrh_username }}
        MAVEN_PASSWORD: ${{ inputs.ossrh_token }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.ossrh_gpg_secret_key_password }} 
