name: Setup JDK for sonatype release
description: 'Setup JDK for sonatype release'

inputs:
  ossrh_gpg_secret_key:
    description: 'OSSRH GPG secret key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17 for Sonatype
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ inputs.ossrh_gpg_secret_key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
