name: Set git user and email
description: 'Set git user and email'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17 for Sonatype
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-executable: gpg2
