name: Publish release to Sonatype
description: 'Publish release to Sonatype'

inputs:
  ossrh_username:
    description: 'OSSRH usernmae'
    required: true
  ossrh_token:
    description: 'OSSRH token'
    required: true
  ossrh_gpg_secret_key_password:
    description: 'OSSRH GPG secret key password'
    required: true
  directory:
    description: 'The directory of the package to be deployed'
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish release to Sonatype
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        mvn -B -U -Possrh,release clean deploy -DskipTests=true -Dstyle.color=always -e -s ${{ github.workspace }}/settings.xml
      env:
        MAVEN_USERNAME: ${{ inputs.ossrh_username }}
        MAVEN_PASSWORD: ${{ inputs.ossrh_token }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.ossrh_gpg_secret_key_password }} 
      