name: Run checks

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: ./.github/workflows/checkout.yml

      - name: Setup JDK with maven
        uses: ./.github/workflows/setup-jdk-with-maven.yml

      - name: Build and check
        uses: ./.github/workflows/build-and-check.yml
