name: Run checks

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK with maven
        uses: ./.github/actions/setup-jdk-with-maven

      - name: Build and check
        uses: ./.github/actions/build-and-check
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
