name: Run checks

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: ./.github/actions/checkout

      - name: Setup JDK with maven
        uses: ./.github/actions/setup-jdk-with-maven

      - name: Build and check
        uses: ./.github/actions/build-and-check
