name: Release new version and Deploy to Maven Central

on:
  workflow_dispatch:
    inputs:
      semverBump:
        description: 'The type of Semantic Version bump (patch, minor or major)'
        required: true
        default: 'patch'

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK with maven
        uses: ./.github/actions/setup-jdk-with-maven

      - name: Create new Semantic Version
        uses: zwaldowski/semver-release-action@v3
        id: semver
        with:
          bump: ${{ github.event.inputs.semverBump }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Versions on all subpackages
        uses: ./.github/actions/update-subpackages-version

      - name: Set git user and email
        uses: ./.github/actions/set-git-username

      - name: Commit updated POMs
        uses: ./.github/actions/commit-updated-version-pom-files

      - name: Setup JDK for sonatype release
        uses: ./.github/actions/setup-jdk-for-sonatype-release-sonatype

      - name: Publish snapshot to Sonatype
        uses: ./.github/actions/publish-release

      - name: Release version on github
        uses: ./.github/actions/publish-release.github
