name: Deploy SNAPSHOT to Sonatype staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: ./.github/workflows/checkout.yml

      - name: Setup JDK with maven
        uses: ./.github/workflows/setup-jdk-with-maven.yml

      - name: Build and check
        uses: ./.github/workflows/build-and-check.yml

      - name: Setup JDK for sonatype release
        uses: ./.github/workflows/setup-jdk-for-sonatype-release.yml

      - name: Publish snapshot to Sonatype
        uses: ./.github/workflows/publish-snapshot.yml
