name: Deploy SNAPSHOT to Sonatype staging

on:
  workflow_dispatch:

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    environment: myenvironment
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK with maven
        uses: ./.github/actions/setup-jdk-with-maven

      - name: Build and check
        uses: ./.github/actions/build-and-check

      - name: Setup JDK for sonatype release
        uses: ./.github/actions/setup-jdk-for-sonatype-release

      - name: Publish snapshot to Sonatype
        uses: ./.github/actions/publish-snapshot-sonatype
