name: Prepare release PR

on:
  workflow_dispatch:
    inputs:
      semverBump:
        description: 'The type of Semantic Version bump (patch, minor or major)'
        required: true
        default: 'patch'
jobs:
  deploy-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK with maven
        uses: ./.github/actions/setup-jdk-with-maven

      - name: Create new Semantic Version
        uses: ./.github/actions/bump-maven-version
        id: semver
        with:
          bump: ${{ github.event.inputs.semverBump }}

      - name: Set git user and email
        uses: ./.github/actions/set-git-username

      - name: Commit updated POMs
        uses: ./.github/actions/create-release-pr
        with:
          github_token: ${{ secrets.GH_STAPI_BOT_TOKEN }}
          bump: ${{ github.event.inputs.semverBump }}
          version: ${{ steps.semver.outputs.version }}

      - name: Set version
        run: echo "${{ steps.semver.outputs.version }}" > version.txt

      - name: Archive version
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: ./version.txt